apiVersion: v1
kind: ConfigMap
metadata:
  name: apicfg
  labels:
    app: webinar
data:
  APP_HOST: "0.0.0.0"
  DB_USER: dbuser
  DB_DATABASE: beersdb
  DB_HOST: db
  DB_PWD: mySuperPwd!!2
  DB_PORT: "5432"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: webinar
      component: api
  template:
    metadata:
      labels:
        app: webinar
        component: api
    spec:
      containers:
      - name: api
        image: beersapi
        envFrom:
          - configMapRef:
              name: apicfg
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 7700
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: webinar
    component: api
  ports:
  - port: 80
    targetPort: 7700
    protocol: TCP
    name: http
